name: Cursor Register

on:
  workflow_dispatch:
    inputs:
      number:
        description: 'Number of accounts to register'
        required: true
        default: '1'

jobs:
  register:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run registration
      run: |
        python cursor_register.py --number ${{ github.event.inputs.number }}

    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: cursor-accounts
        path: cursor_accounts.csv
